tasks.register('runClient') {
    dependsOn ':exodus-survival:runClient'
    group = 'exodus'
    description = 'Run Minecraft client with Exodus mods'
}

subprojects {
    plugins.withId('fabric-loom') {
        afterEvaluate {
            if (project.name != 'exodus-survival') {
                tasks.named('runClient') { enabled = false }
                tasks.named('runServer') { enabled = false }
            }
        }
    }
}