plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.modpack_version
group = project.maven_group

base {
    archivesName = 'exodus-survival'
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "exodus-survival" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // Добавляем exodus-core как зависимость проекта
    implementation project(path: ':exodus-core', configuration: 'namedElements')
}

processResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    it.options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    from("LICENSE") {
        rename { "${it}_exodus-survival"}
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'exodus-survival'
            from components.java
        }
    }

    repositories {
        maven {
            url = layout.buildDirectory.dir('repo')
        }
    }
}