plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.modpack_version
group = project.maven_group

base {
    archivesName = 'exodus-core'
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    maven { url 'https://maven.ladysnake.org/releases' }  // ✅ ДОБАВЛЕНО
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "exodus-core" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-base:${cardinal_components_version}"
    modImplementation "dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${cardinal_components_version}"
}

processResources {
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'com.exodus'
            artifactId = 'exodus-core'
            version = project.modpack_version
            from components.java
        }
    }
    repositories {
        mavenLocal()
    }
}